package exceptions

fun main() {
    val exception = NewException()
    exception.main()
}